// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VectorIdentityAPI.Database;

namespace VectorIdentityAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VectorIdentityAPI.Database.Arc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AngleEnd")
                        .HasColumnType("float");

                    b.Property<double>("AngleStart")
                        .HasColumnType("float");

                    b.Property<int?>("ProjectDataId")
                        .HasColumnType("int");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDataId");

                    b.ToTable("Arc");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.ComparisonData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectAId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAId");

                    b.HasIndex("ProjectBId");

                    b.ToTable("ComparisonData");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Direction")
                        .HasColumnType("float");

                    b.Property<double>("Magnitude")
                        .HasColumnType("float");

                    b.Property<int?>("ProjectDataId")
                        .HasColumnType("int");

                    b.Property<double>("X1")
                        .HasColumnType("float");

                    b.Property<double>("X2")
                        .HasColumnType("float");

                    b.Property<double>("Y1")
                        .HasColumnType("float");

                    b.Property<double>("Y2")
                        .HasColumnType("float");

                    b.Property<double>("Z1")
                        .HasColumnType("float");

                    b.Property<double>("Z2")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDataId");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArcAId")
                        .HasColumnType("int");

                    b.Property<int?>("ArcBId")
                        .HasColumnType("int");

                    b.Property<int?>("ComparisonDataId")
                        .HasColumnType("int");

                    b.Property<int?>("LineAId")
                        .HasColumnType("int");

                    b.Property<int?>("LineBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArcAId");

                    b.HasIndex("ArcBId");

                    b.HasIndex("ComparisonDataId");

                    b.HasIndex("LineAId");

                    b.HasIndex("LineBId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.ProjectData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CorrectnessScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("IdentityScore")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Original")
                        .HasColumnType("bit");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectSetId");

                    b.ToTable("ProjectData");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.ProjectSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ProjectSet");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.Arc", b =>
                {
                    b.HasOne("VectorIdentityAPI.Database.ProjectData", null)
                        .WithMany("Arcs")
                        .HasForeignKey("ProjectDataId");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.ComparisonData", b =>
                {
                    b.HasOne("VectorIdentityAPI.Database.ProjectData", "ProjectA")
                        .WithMany()
                        .HasForeignKey("ProjectAId");

                    b.HasOne("VectorIdentityAPI.Database.ProjectData", "ProjectB")
                        .WithMany()
                        .HasForeignKey("ProjectBId");

                    b.Navigation("ProjectA");

                    b.Navigation("ProjectB");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.Line", b =>
                {
                    b.HasOne("VectorIdentityAPI.Database.ProjectData", null)
                        .WithMany("Lines")
                        .HasForeignKey("ProjectDataId");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.Match", b =>
                {
                    b.HasOne("VectorIdentityAPI.Database.Arc", "ArcA")
                        .WithMany()
                        .HasForeignKey("ArcAId");

                    b.HasOne("VectorIdentityAPI.Database.Arc", "ArcB")
                        .WithMany()
                        .HasForeignKey("ArcBId");

                    b.HasOne("VectorIdentityAPI.Database.ComparisonData", null)
                        .WithMany("Matches")
                        .HasForeignKey("ComparisonDataId");

                    b.HasOne("VectorIdentityAPI.Database.Line", "LineA")
                        .WithMany()
                        .HasForeignKey("LineAId");

                    b.HasOne("VectorIdentityAPI.Database.Line", "LineB")
                        .WithMany()
                        .HasForeignKey("LineBId");

                    b.Navigation("ArcA");

                    b.Navigation("ArcB");

                    b.Navigation("LineA");

                    b.Navigation("LineB");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.ProjectData", b =>
                {
                    b.HasOne("VectorIdentityAPI.Database.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("VectorIdentityAPI.Database.ProjectSet", "ProjectSet")
                        .WithMany()
                        .HasForeignKey("ProjectSetId");

                    b.Navigation("Owner");

                    b.Navigation("ProjectSet");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.ProjectSet", b =>
                {
                    b.HasOne("VectorIdentityAPI.Database.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.ComparisonData", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("VectorIdentityAPI.Database.ProjectData", b =>
                {
                    b.Navigation("Arcs");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
